#!/bin/bash
set -e

cd $(dirname $0)

./build

echo "----------------------------------------------------"

ls -ltrh /etc/resolv.conf
cat /etc/resolv.conf
uname -a

docker info
docker pull hello-world


./integration
